ip: 172.28.160.1
spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service-route
          uri: lb://selmag-catalogue-service
          predicates:
            - Host=catalogue.api.selm.ag.${ip}.nip.io
        - id: feedback-service-route
          uri: lb://selmag-feedback-service
          predicates:
            - Host=feedback.api.selm.ag.${ip}.nip.io
        - id: manager-app-route
          uri: lb://selmag-manager-app
          predicates:
            - Host=manager.selm.ag.${ip}.nip.io
        - id: customer-app-route
          uri: lb://selmag-customer-app
          predicates:
            - Host=customer.selm.ag.${ip}.nip.io
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${ip}:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://${ip}:8082/realms/selmag
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: kaKBJ6Pc9mPldygbbI5SgWkZWo1ewk5y
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: selmag-api-gateway
  boot:
    admin:
      client:
        enabled: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: ${ip}
  client:
    service-url:
      defaultZone: http://${ip}:8761/eureka/
    registryFetchIntervalSeconds: 1